[project]
name = "pydmc"
description = "Python implementation of DMC (Dynamic Models of Choice) R package, specifically for RDEX-ABCD model"
version = "0.1.0"
channels = ['conda-forge']
platforms = ['linux-64', 'osx-64', 'osx-arm64', 'win-64']

[dependencies]
python = "~=3.10.0"
ruff = "*"
pip = ">=25.3,<26"
ipykernel = ">=7.1.0,<8"
numpy = ">=2.2.6,<3"
pandas = ">=2.3.3,<3"
seaborn = ">=0.13.2,<0.14"
cmdstanpy = ">=1.3.0,<2"

[pypi-dependencies]
mkdocs = "*"
python-dotenv = "*"
pydmc = { path = ".", editable = true }
